//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.Ingredients = new HashSet<Ingredient>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public bool IsVegetarian { get; set; }
        public bool IsGlutenFree { get; set; }
        public Nullable<int> PrepTime { get; set; }
        public Nullable<int> CookTime { get; set; }
        public Nullable<int> NbrOfPeople { get; set; }
        public Nullable<int> NbrOfSteps { get; set; }
    
        public virtual ICollection<Ingredient> Ingredients { get; set; }
    }
}
